"""Additional screenshot chapters for the four-station participant guide."""
extra_sections = [
    ("Cyber Security: kuis kolaborasi", "desktop-cyber-quiz.png",
     "Navigator dan pilihan jawaban Cyber Security.",
     "<p>Pilih Cyber Security, baca aturan, lalu tekan Mulai Demo. Jawab enam soal A–D dalam empat menit. Tidak ada rotasi anggota; satu orang dapat mensimulasikan diskusi tim.</p><p>Jawaban dapat diganti sebelum submit. Pastikan status Tersimpan, lalu pilih Kirim Semua Jawaban Tim dan konfirmasikan. Benar bernilai 10 poin, salah/kosong 0; bonus mengikuti aturan yang ditampilkan. Kunci dan pembahasan tersedia setelah selesai.</p>"),
    ("Networking: Signal Check", "desktop-networking-stage-1.png",
     "Tahap 1 menampilkan soal aktif berurutan dan timer tahap.",
     "<p>Durasi keseluruhan Networking adalah 5 menit. Tahap 1 berisi tiga pilihan ganda A–E, masing-masing 10 poin, dengan waktu 90 detik.</p><p>Jawab berurutan. Pilihan langsung terkunci setelah tersimpan dan soal berikutnya muncul. Setelah semua soal selesai, pilih Selesaikan Tahap 1 dan konfirmasikan. Tekan Mulai Tahap 2 pada halaman transisi. Deadline keseluruhan tetap berjalan selama transisi.</p>"),
    ("Networking: True or Trap", "desktop-networking-stage-2.png",
     "Tahap 2 memakai jawaban Benar/Salah.",
     "<p>Tahap 2 berisi empat pernyataan Benar/Salah, masing-masing 10 poin, dengan waktu 60 detik. Jawab berurutan; pilihan yang tersimpan langsung dikunci.</p><p>Konfirmasikan penyelesaian, lalu tekan Mulai Tahap 3. Jika waktu tahap 1 atau 2 habis, jawaban yang tersimpan dikunci dan halaman transisi tersedia. Tahap berikutnya dimulai setelah konfirmasi, sepanjang deadline keseluruhan belum habis.</p>"),
    ("Networking: Case Signal", "desktop-networking-stage-3.png",
     "Lima isian singkat pada tahap ketiga.",
     "<p>Tahap 3 berisi lima isian singkat, masing-masing 6 poin, dengan waktu maksimal 150 detik. Ketik jawaban, tunggu penyimpanan, lalu gulir untuk menjawab soal berikutnya. Isian dapat diedit sebelum submit.</p><p>Penilaian latihan menggunakan kunci serta variasi jawaban yang diterima, tanpa membedakan kapitalisasi dan spasi berlebih. Pilih Kirim Semua Jawaban dan konfirmasikan. Ketika deadline tahap atau keseluruhan habis, jawaban tersimpan dinilai tanpa bonus waktu.</p>"),
    ("Networking: hasil dan Stempel Latihan", "desktop-networking-result.png",
     "Rincian nilai tiap tahap dan status Stempel Latihan.",
     "<p>Nilai tahap maksimal berturut-turut 30, 40, dan 30. Skor akhir menambahkan bonus sisa waktu keseluruhan; penalti demo 0.</p><p>Minimal empat dari lima jawaban tahap 3 yang benar memperoleh Stempel Latihan. Hasil otomatis ini khusus latihan; lomba resmi memakai verifikasi fasilitator. Pembahasan baru muncul setelah seluruh percobaan selesai.</p>"),
    ("Hardware: memilih rakitan", "desktop-hardware-components.png",
     "Pilihan komponen katalog internal, total harga, dan alasan rakitan.",
     "<p>Pilih Hardware, baca aturan dan studi kasus, lalu pilih CPU, motherboard, GPU, RAM, storage, dan PSU. Durasi lima menit termasuk membaca. Harga dan performa adalah data sintetis latihan.</p><p>Target: budget USD 1500, CPU minimal 1000, GPU minimal 2000. Cocokkan socket CPU/motherboard dan jenis RAM. PSU perlu memenuhi daya CPU + GPU + cadangan 100 W. Total harga mengikuti pilihan.</p><p>Tulis alasan singkat, pastikan penyimpanan, lalu kirim dan konfirmasikan. Alasan disimpan tanpa nilai otomatis. Demo tidak memerlukan BuildCores atau upload bukti.</p>"),
    ("Hardware: membaca hasil rakitan", "desktop-hardware-result.png",
     "Ringkasan skor serta rincian hasil simulasi Hardware.",
     "<p>Hasil merinci kompatibilitas, budget, CPU/GPU, kelengkapan, dan efisiensi. Bonus waktu maksimal 5 sesuai proporsi waktu tersisa; skor akhir maksimal 100.</p><p>Gulir untuk melihat pemeriksaan socket/RAM/PSU dan contoh konfigurasi yang memenuhi target. Jika waktu habis, komponen tersimpan tetap dievaluasi dengan bonus nol. Hasil ini simulasi, bukan verifikasi panitia. Alur resmi memakai BuildCores, screenshot, dan peninjauan panitia.</p>"),
    ("Untuk admin: mengatur Masa Demo", "desktop-admin-demo-only.png",
     "Pengaturan Akses Website dengan Masa Demo aktif; akun pada screenshot adalah akun pengujian.",
     "<p>Login melalui Login Admin, lalu pilih Pengaturan Akses Website dari menu panel. Pilih Masa Demo, tekan Simpan Pengaturan Akses, dan konfirmasikan.</p><p>Perubahan berlaku tanpa restart. Pengunjung umum hanya dapat menggunakan demo dan panduan; akses peserta, API, leaderboard, dan berkas lomba ditutup. Admin aktif tetap dapat memakai panel dan memeriksa alur resmi. Jika ada sesi RUNNING, selesaikan atau batalkan dahulu.</p><p>Untuk membuka lomba kembali, pilih Normal dan simpan. Peserta memasukkan kode akses kembali. Ketersediaan demo pada mode Normal mengikuti DEMO_ENABLED. Riwayat perubahan serta statistik demo ditampilkan terpisah dari hasil resmi.</p>"),
]
